Add Dockerfile
Steffo99/greed pull request #102
Opened 2021-04-23 23:54 UTC by masterbpro

2021-04-24 21:05 UTC, Steffo99 requested changes
Hi! Thanks for the contribution!

2021-04-24 21:05 UTC, Steffo99 commented on Dockerfile
> +LABEL maintainer="ste.pigozzi@gmail.com" \
I don't know much about Dockerfiles, are you sure it's a good idea listing me as the maintainer?

2021-04-24 21:05 UTC, Steffo99 commented on README.md
> +      ```
Is there a full length alternative to these options?

I know `-d` detaches the console from the container as soon as it's started, but I have no idea of what the others mean.

By using the full length options (the ones starting with two dashes, like `--detach`, it would be obvious without having to open the man page :)

2021-04-25 15:41 UTC, masterbpro commented on Dockerfile
> +LABEL maintainer="ste.pigozzi@gmail.com" \
It is optional argument, you can delete them

2022-02-20 16:11 UTC, Steffo99 commented
I'm working on an improved version of this PR over at #168.

2022-02-20 16:11 UTC, closed without merging