Add Language PT_BR
Steffo99/greed pull request #132
Opened 2021-05-14 04:48 UTC by eufelipemateus

Create br.py - Languagem Portuguese Brasilian

2021-05-19 18:29 UTC, Steffo99 commented
Thanks for the contribution! 

I'll have a look at this as soon as I have some time :sob:

2021-05-19 21:33 UTC, Steffo99 requested changes
Thanks!

There are a few things left to polish before merging this pull request!

Have a look:

2021-05-19 21:33 UTC, Steffo99 commented on config/template_config.toml
> +# br - Brasilian by https://github.com/eufelipemateus
Please move this to the bottom of the list of languages; it's going to be the latest language added, not the first!

2021-05-19 21:33 UTC, Steffo99 commented on config/template_config.toml
> +default_language = "br"
```suggestion
default_language = "it"
```

Please don't change the default language :)

2021-05-19 21:33 UTC, Steffo99 commented on config/template_config.toml
> +enabled_languages = ["br","it", "en", "uk", "ru", "zh_cn", "he", "es_mx"]
Same thing as earlier.

```suggestion
enabled_languages = ["it", "en", "uk", "ru", "zh_cn", "he", "es_mx", "br"]
```

Additionally, shouldn't Brasilian be `pt_br`?

2021-05-19 21:33 UTC, Steffo99 commented on strings/br.py
> +in_stock_format_string = "{quantity} Disponível"
```suggestion
in_stock_format_string = "{quantity} disponível"
```

This should probably be lowercase.

2021-05-19 21:33 UTC, Steffo99 commented on strings/br.py
> +in_cart_format_string = "{quantity} no Carrinho"
```suggestion
in_cart_format_string = "{quantity} no carrinho"
```

Same.

2021-05-19 21:33 UTC, Steffo99 commented on strings/br.py
> +conversation_open_admin_menu = "Você é um  💼 <b>Gerente</b> desta loja!\n" \
```suggestion
conversation_open_admin_menu = "Você é um 💼 <b>Gerente</b> desta loja!\n" \
```

There's an extra space here.

2021-05-19 21:33 UTC, Steffo99 commented on strings/br.py
> +                  "💼 Ele ficará visível para os gerentes da loja.\n" \
```suggestion
                  "Ele ficará visível para os 💼 Gerentes da loja.\n" \
```
I think the emoji should be here, but i'm not sure.

2021-05-19 21:33 UTC, Steffo99 commented on strings/br.py
> +                        " e para 💼 Admins no log de transações."
```suggestion
                        " e para 💼 Gerentes no log de transações."
```
This would be consistent with the rest of the translation.

2021-05-19 21:33 UTC, Steffo99 commented on strings/br.py
> +notification_order_completed = "Seu Pedido foi completado!\n" \
```suggestion
notification_order_completed = "Seu pedido foi completado!\n" \
```
Case.

2021-05-19 21:33 UTC, Steffo99 commented on strings/br.py
> +notification_transaction_created = "ℹ️  Uma nova transação foi aplicada à sua carteira:\n" \
```suggestion
notification_transaction_created = "ℹ️ Uma nova transação foi aplicada à sua carteira:\n" \
```

2021-05-19 21:33 UTC, Steffo99 commented on strings/br.py
> +           'Affero General Public License 3.0</a>.\n'
You forgot to translate these strings :)

2021-05-19 21:33 UTC, Steffo99 commented on strings/br.py
> +                               "Para reiniciar a conversa, envie o comando / start novamente."
```suggestion
                               "Para reiniciar a conversa, envie o comando /start novamente."
```

2021-05-19 22:06 UTC, eufelipemateus commented on config/template_config.toml
> +# br - Brasilian by https://github.com/eufelipemateus
ok

2021-05-19 22:07 UTC, eufelipemateus commented on strings/br.py
> +           'Affero General Public License 3.0</a>.\n'
I thought it wasn't necessary

2021-05-24 17:59 UTC, Steffo99 requested changes
Just a few lines to fix and then it's good to go! :)

2021-05-24 17:59 UTC, Steffo99 commented on strings/pt_br.py
> +                           "If you find any, please report them at https://github.com/Steffo99/greed/issues."
This line is not translated :)

2021-05-24 17:59 UTC, Steffo99 commented on strings/pt_br.py
> +order_format_string = "by {user}\n" \
This line doesn't seem translated :)

2021-05-25 23:17 UTC, merged

2021-05-25 23:17 UTC, Steffo99 commented
Thanks for everything!