removed unused imports and refactored imports
Steffo99/greed pull request #145
Opened 2021-08-03 01:56 UTC by rashidkalwar

remove the unused imports and tried to make the code a little bit concise. 
please review and provide feed back.

2021-08-07 23:41 UTC, Steffo99 requested changes
Thanks for the contribution! :D

Usually, when you make a pull request, you try to minimize the amount of changes unrelated to its topic :)

I left you a few suggestions of edits to undo before this pull request can be merged ^_^

2021-08-07 23:41 UTC, Steffo99 commented on .gitignore
> +Pipfile
Please do not introduce additional changes in pull requests :)

```suggestion

```

2021-08-07 23:41 UTC, Steffo99 commented on core.py
> +import sqlalchemy, sqlalchemy.ext.declarative as sed
Can you split this into multiple lines?

```suggestion
import sqlalchemy
import sqlalchemy.ext.declarative as sed
```

It's just a matter of personal preference, it should work anyways :)

2021-08-07 23:41 UTC, Steffo99 commented on duckbot.py
> +import sys, time
Same thing as above :)

```suggestion
import sys
import time
```

2021-08-07 23:41 UTC, Steffo99 commented on worker.py
> +import os, sys, datetime
```suggestion
import os
import sys
import datetime
```

2021-08-08 07:46 UTC, rashidkalwar commented
@Steffo99 I have made commits of your suggestions, please review again.

2021-08-13 13:58 UTC, Steffo99 commented on duckbot.py
> +import sys, time
Please apply this too :)

2021-08-13 13:59 UTC, Steffo99 commented
Thanks! :D

2021-08-17 00:15 UTC, merged