Adding Hebrew language support
Steffo99/greed pull request #70
Opened 2020-08-22 21:53 UTC by netanelkoli

2020-08-24 22:20 UTC, Steffo99 requested changes
![image](https://user-images.githubusercontent.com/1540885/91101987-90e2ee80-e668-11ea-95c3-6a6454f12e92.png)

Editing RTL text is really difficult for me, as I am not used to it...

Could you please ensure all emojis are on the correct side of the message and they have a space between them and the following text?

2020-08-25 06:47 UTC, netanelkoli commented
Did my best, but it looks like one or two emojis just cant be aligned. I added a space between them. Please review.

2020-08-25 23:55 UTC, Steffo99 approved these changes
Good job, thanks! :D

2020-08-25 23:55 UTC, merged

2020-08-25 23:57 UTC, Steffo99 commented
By the way, you may want to check your git config, your last commit was authored by an email not registered to any GitHub account :)